[project]
name = "o-platy60-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.128.0",
    "ipython>=9.9.0",
    "supabase>=2.27.2",
    "uvicorn>=0.40.0",
]
